### ISSUE TITLE
Create User + Listing models

### ISSUE THREAD

**Issue by Lamm9** [CarlyGallagher/dream-team#29]

**Comment by kaleemullah786** [comment]
hey, can i work on it

**Comment by Lamm9** [comment]
sorry buddy, Carly's idea.On Jun 1, 2023, at 7:02 PM, Kaleem Ullah ***@***.***> wrote:hey, can i work on it—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
